alias: "AI: 門口動靜通知"
description: ""
triggers:
  - trigger: state
    entity_id:
      - camera.aarlo_main_door		# entity ID of your security camera
    to: recording
conditions: []
actions:
  - action: camera.snapshot
    target:
      device_id: xxxxxxxxxxxxxxxxxx # device ID of your security camera
    data:
      filename: /config/www/tmp/snapshot-doorbell.jpg
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
  - action: ai_task.generate_data
    data:
      instructions: >-
        想像你係一個智能家居助理。 宜家你要向用家報告大門口人員出入嘅狀況。 

        門口鏡頭嘅拍攝時間為 {{ states('sensor.aarlo_last_main_door') }}  # your security camera's photo taken time

        位於右邊嘅門屬於鄰居。用家屋企同鄰居屋企嘅家人同傭工都有鑰匙直接入屋。

        請根據呢啲資訊，以香港口音嘅廣東話向用家報告最新狀態。 

        如果上述大門口相機影到畫面嘅時間同宜家呢一刻吻合， 請仔細形容畫面內人物嘅性別、身高及臉容特徵，以及佢嘅動作，進入或離開邊一個單位。
        鏡頭可能會影到距離較遠嘅鄰居出入，以及去左右邊垃圾房倒垃圾嘅情況。如果拍到嘅人物太細，睇唔到臉容，請不用理會。

        回應內容將會以香港廣東話口語通知方式傳送到用家手機， 由於需要預留照片空間， 請將內容保持極之簡潔， 長度一定要保持喺 2 句句子以內。
        內容如要提及影片分析到嘅時間， 需與上述提及嘅拍攝時間相同。 歡迎使用各種表情符號，令用家更加留意。 
      task_name: 分析門口影像
      entity_id: ai_task.google_ai_task # use Google Gemini to analyze the photo using the above prompts
      attachments:
        media_content_id: media-source://camera/camera.aarlo_main_door
        media_content_type: image/jpeg
        metadata:
          title: Main Door Doorbell Camera
          thumbnail: /api/camera_proxy/camera.aarlo_main_door
          media_class: video
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://camera
    response_variable: response
  - data:
      message: "{{response.data}}"          # forming the phone notification message body
      title: Home Assistant 通知
      data:
        image: /local/tmp/snapshot-doorbell.jpg
        video: "{{state_attr('sensor.aarlo_last_main_door','video_url')}}"
        url: "{{state_attr('sensor.aarlo_last_main_door','video_url')}}"
        clickAction: "{{state_attr('sensor.aarlo_last_main_door','video_url')}}"
    enabled: true
    action: notify.mobile_app_pixel_9_pro_fold      # change this to your phone's notify target
  - action: mqtt.publish
    metadata: {}
    data:
      topic: homeassistant/markdown_main_door_summary   # use MQTT to publish analysis contents generated by AI to this topic's MQTT entity to keep track of changes
      payload: "{{ response.data }}"
      retain: true
mode: single
